name: TokyoAuto

on: 
  schedule:
    - cron: '0 0 * * *'
    
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install pandas
          pip install matplotlib
          pip install japanize-matplotlib
          pip install urllib3
          pip install opencv-python
          pip install slackweb
          pip install requests
          
      - name: Run daily-week.py
        run: |
          python tokyo/daily-week.py

#       - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
#         run: |
#           git config user.name "keikagawa"
#           git config user.email "gerogero7429@gmail.com"
#           git add .
#           git commit -m "Update graph"
#           git pull
      #     git push origin master

      - name: Run send.py
        run: |
          python send.py
